### ISSUE TITLE
Add ability to change where notices are displayed

### ISSUE THREAD

**Issue by dextermb** [ninetynine/react-notices#2]
Currently notices appear from the bottom right. What about if people want them to come from:

* Top left
* Top center
* Top right
* Bottom left
* Bottom center
* Left center
* Right center

This could be done with a `position` prop on the `Provider`. I'd like to see an implementation where you can give a `string`:

```jsx
// Top center
<Provider
  position={'top'}
/>

// Top left
<Provider
  position={'top left'}
/>

// Left center
<Provider
  position={'left'}
/>
```

This would append a class to the `notice-container` class. Following the naming convention it would look like:

```css
.display-top-center
.display-top-left
.display-left-center
```

For each different position a different set of default animations would have to be created. I suggest moving the default animation(s) to a new file to make this cleaner and easier to maintain.

**Comment by dextermb** [comment]
I've begun implementing this feature.

**Comment by sergeycw** [comment]
Hi! Wait for me please, I'll do it today.

**Comment by dextermb** [comment]
> Hi! Wait for me please, I'll do it today.

Take a stab at it. 👍

**Comment by dextermb** [comment]
@sergeycw How is your implementation of this coming along?
I've got a PR (#3) open for it. How does yours compare?

**Comment by sergeycw** [comment]
@dextermb I just got my hands on the laptop,  but as I see you already implement this functionality

**Comment by dextermb** [comment]
> @dextermb I just got my hands on the laptop, but as I see you already implement this functionality

If you want to have a go feel free. I'll leave my PR there until tomorrow 👍
