### ISSUE TITLE
Add success theme

### ISSUE THREAD

**Issue by dextermb** [ninetynine/react-notices#4]
* Add `success` to `theme` prop type options
* Add `display-success` stylings to `notice.scss`

**Comment by arjbholu** [comment]
Hey, @dextermb Can I take this up?

**Comment by dextermb** [comment]
> Can you tell me what background-color you need for success theme?

A neutral green. I've been using [open color](https://yeun.github.io/open-color/) for a while, it's great

**Comment by dextermb** [comment]
@arjbholu Implemented as of `1.3.0` 🎉
